<?php

namespace VMS\VitrineBundle\Repository;

/**
 * OrigineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrigineRepository extends \Doctrine\ORM\EntityRepository
{
}
